### ISSUE TITLE
Error on Xmpp.Open(username, token); in HarmonyClient.cs any ideas on the problem

### ISSUE THREAD

**Issue by TomFitzmorris** [hdurdle/harmony#1]
System.IndexOutOfRangeException was unhandled
  Message=Index was outside the bounds of the array.
  Source=Harmony
  StackTrace:
       at HarmonyHub.HarmonyClientConnection.HarmonyClientConnection_OnSocketError(Object sender, Exception ex) in C:\Documents and Settings\Chris\Desktop\Harmony\HarmonyHub\HarmonyClientConnection.cs:line 28
       at agsXMPP.XmppClientConnection.SocketOnError(Object sender, Exception ex)
       at agsXMPP.net.BaseSocket.FireOnError(Exception ex)
       at agsXMPP.net.ClientSocket.Connect()
       at agsXMPP.XmppConnection.SocketConnect()
       at agsXMPP.XmppConnection.SocketConnect(String server, Int32 port)
       at agsXMPP.XmppClientConnection.OpenSocket()
       at agsXMPP.XmppClientConnection._Open()
       at agsXMPP.XmppClientConnection.Open(String username, String password)
       at HarmonyHub.HarmonyClient..ctor(String ipAddress, Int32 port, String token) in C:\Documents and Settings\Chris\Desktop\Harmony\HarmonyHub\HarmonyClient.cs:line 48
       at HarmonyHub.HarmonyAuthenticationClient..ctor(String ipAddress, Int32 port) in C:\Documents and Settings\Chris\Desktop\Harmony\HarmonyHub\HarmonyAuthenticationClient.cs:line 14
       at HarmonyConsole.Program.LoginToLogitech(String email, String password, String ipAddress, Int32 harmonyPort) in C:\Documents and Settings\Chris\Desktop\Harmony\HarmonyConsole\Program.cs:line 177
       at HarmonyConsole.Program.Main(String[] args) in C:\Documents and Settings\Chris\Desktop\Harmony\HarmonyConsole\Program.cs:line 81
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by mheydman** [comment]
A little late to the game perhaps, but I figured out this issue.

In Program.cs there is a mysterious call to Dns.GetHostEntry() on line 82. Nothing is done with the return value so the line appears to be something that is a work-in-progress. This call was throwing an error for me, so I commented it out.

My next issue was the error described earlier in this thread, which appears to be an issue with agsXMPP.net.ClientSocket.Connect(). I looked at the agsXMPP source code and the first line in that Connect() method is a call to... you guessed it... Dns.GetHostEntry().

Since I am on a LAN and there is no name resolution set up for my internal IP's, I figured that's what was maybe causing the issue.

SOLUTION: I added a line in my hosts file (located in %WINDIR%\system32\drivers\etc) mapping my Harmony Hub's IP to a name. Once I did that, I was able to establish my initial connection to the hub and return basic status.

**Comment by yourbuddypal** [comment]
@mheydman Excellent post.  That worked for me as well!

**Comment by swaner** [comment]
You are a smart man @mheydman. Works great for me also, this should really be included in the readme file. Not easy to find in a closed issue.

**Comment by Lakritzator** [comment]
I actually fixed this in my fork, unfortunately I didn't have a lot of time to check everything and create a PR...

Maybe this helps too?
https://github.com/Lakritzator/harmony

> Changed the agsXMPP to Loamen.agsXMPP as this version doesn't have issues with Harmony-Hubs which don't have a hostname (IP only). I modified the HarmonyClient so that it doesn't use RegEx on the XML-string, but uses the build-in functionality that was written for such cases. Also fixed a problem where the OnIq switch always went into the GetCurrentActivity case at the first call, as this was the default value of _clientCommand.
