### ISSUE TITLE
System.Net.Sockets.SocketException: No such host is known

### ISSUE THREAD

**Issue by sarfrazsheikh** [hdurdle/harmony#4]
Thanks for sharing code. I am seeing this issue while running code,
 when I provide my username, password and ip address.
the ip address used is local ip for  harmony hub.
Please suggest what can fix that.

Unhandled Exception: System.Net.Sockets.SocketException: No such host is known
   at System.Net.Dns.InternalGetHostByAddress(IPAddress address, Boolean includeIPv6)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at HarmonyConsole.Program.Main(String[] args) in C:\Data\harmony-master\HarmonyConsole\Program.cs:line 80

**Comment by hdurdle** [comment]
This is a DNS issue, my code makes a call to GetHostEntry (as does the underlying library that talks to the hub). You'll need working DNS resolution or an entry in your hosts file.

See https://github.com/hdurdle/harmony/wiki/Exception:-No-such-host-is-known
